<?php
$contacts = $this->getContacts();
?>


<div id="contactslist">
    <h2>Empty</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php                
                foreach($contacts as $contact){
                    ?>
                    <tr>
                        <td><?php echo $contact->getName(); ?></td>
                        <td><?php echo $contact->getEmail(); ?></td>
                    </tr>
                    <?php
                }
            ?>
<!--            {% for contact in contacts %}
                <tr>
                    <td>{{ contact.getName }}</td>
                    <td>{{ contact.getEmail }}</td>
                </tr>
            {% endfor %}-->
        </tbody>        
    </table>
</div>
